### ISSUE TITLE
Kotlin Internal Error when trying to run any test

### ISSUE THREAD

**Issue by PatrykMilewski** [RaspberryWallet/Backend#83]
This problem occured after merging current master with my feature branch in this commit:
e277a27a59371d01166816b319dcc56d7da71919

Output full version:
https://pastebin.com/9Hh7P23X

Shortened version:
```
Error:Kotlin: [Internal Error] java.lang.IllegalStateException: Backend Internal error: Exception during code generation
Cause: Back-end (JVM) Internal error: Couldn't inline method call 'consumeEach' into
public final fun doResume(data: kotlin.Any?, throwable: kotlin.Throwable?): kotlin.Any? defined in io.raspberrywallet.server.KtorServer.mainModule.<anonymous>.<closure-KtorServer$mainModule$6$26>
{
                blockChainSyncProgressionChannel.consumeEach { progress ->
                    outgoing.send(Frame.Text("$progress"))
                    if (progress == 100) close()
                }
            }
Cause: Method inlining consumeEach { progress ->
                    outgoing.send(Frame.Text("$progress"))
                    if (progress == 100) close()
                }: couldn't inline method call
Cause: consumeEach (Lkotlinx/coroutines/channels/ReceiveChannel;Lkotlin/jvm/functions/Function1;Lkotlin/coroutines/Continuation;Lio/raspberrywallet/server/KtorServer$mainModule$6$26;Lio/ktor/websocket/DefaultWebSocketServerSession;)Ljava/lang/Object;:
  @Lkotlinx/coroutines/ObsoleteCoroutinesApi;() // invisible
  @Lorg/jetbrains/annotations/Nullable;() // invisible
    @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 0
    @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 1
    @Lorg/jetbrains/annotations/NotNull;() // invisible, parameter 2
    TRYCATCHBLOCK L0 L1 L2 java/lang/Throwable
    TRYCATCHBLOCK L3 L4 L2 java/lang/Throwable


[...]


   L16
    NEW java/lang/IllegalStateException
    DUP
    LDC "call to 'resume' before 'invoke' with coroutine"
    INVOKESPECIAL java/lang/IllegalStateException.<init> (Ljava/lang/String;)V
    ATHROW
   L44
    LOCALVARIABLE progress I L32 L37 14
    LOCALVARIABLE $i$a$1$consumeEach I L32 L37 15
    LOCALVARIABLE e$iv Ljava/lang/Object; L31 L38 13
    LOCALVARIABLE $receiver$iv Lkotlinx/coroutines/channels/ReceiveChannel; L22 L27 10
    LOCALVARIABLE $i$a$4$consume I L22 L27 17
    LOCALVARIABLE e$iv$iv Ljava/lang/Throwable; L41 L7 16
    LOCALVARIABLE cause$iv$iv Ljava/lang/Throwable; L20 L40 9
    LOCALVARIABLE $receiver$iv$iv Lkotlinx/coroutines/channels/ReceiveChannel; L19 L40 8
    LOCALVARIABLE $i$f$consume I L19 L40 18
    LOCALVARIABLE $receiver$iv Lkotlinx/coroutines/channels/ReceiveChannel; L9 L44 0
    LOCALVARIABLE action$iv Lkotlin/jvm/functions/Function1; L9 L44 1
    LOCALVARIABLE $i$f$consumeEach I L18 L16 19
    LOCALVARIABLE $continuation$iv Lkotlin/coroutines/Continuation; L11 L16 5
    MAXSTACK = 4
    MAXLOCALS = 20
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.wrapException(MethodInliner.kt:817)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:114)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:67)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.inlineCall(InlineCodegen.kt:277)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.performInline(InlineCodegen.kt:158)
	... 138 more
Caused by: java.lang.RuntimeException: Trying to access skipped parameter: Lkotlin/jvm/functions/Function1; at 1
	at org.jetbrains.kotlin.codegen.inline.LocalVarRemapper.remap(LocalVarRemapper.kt:80)
	at org.jetbrains.kotlin.codegen.inline.LocalVarRemapper.visitVarInsn(LocalVarRemapper.kt:103)
	at org.jetbrains.kotlin.codegen.inline.RemapVisitor.visitVarInsn(RemapVisitor.java:53)
	at org.jetbrains.org.objectweb.asm.tree.VarInsnNode.accept(VarInsnNode.java:86)
	at org.jetbrains.org.objectweb.asm.tree.InsnList.accept(InsnList.java:162)
	at org.jetbrains.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:817)
	at org.jetbrains.kotlin.codegen.inline.MethodInliner.doInline(MethodInliner.kt:111)
	... 141 more
```

**Comment by PatrykMilewski** [comment]
After reimporting modules and `chown user Backend -R` the problem with kotlin resolved, but still tests does not run, due to problems with Java classes visibility https://pastebin.com/sygRmyfR (strange). I will look into this tommorow, it's probably my environment specific problem, anyways still keeping #84 as locked

**Comment by PatrykMilewski** [comment]
I will try to fix it today, but I'm not sure if I manage to get spare time for this, if not I will look into this tommorow

**Comment by PatrykMilewski** [comment]
I'm not sure what it was, but after fresh clone, it works without a problem
